---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.19.0
  name: simplyblockdevices.simplyblock.simplyblock.io
spec:
  group: simplyblock.simplyblock.io
  names:
    kind: SimplyBlockDevice
    listKind: SimplyBlockDeviceList
    plural: simplyblockdevices
    singular: simplyblockdevice
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: SimplyBlockDevice is the Schema for the simplyblockdevices API
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: spec defines the desired state of SimplyBlockDevice
            properties:
              clusterName:
                type: string
              includeStats:
                type: boolean
              nodeUUID:
                type: string
              statsHistoryInSeconds:
                format: int32
                type: integer
            required:
            - clusterName
            type: object
          status:
            description: status defines the observed state of SimplyBlockDevice
            properties:
              nodes:
                items:
                  properties:
                    devices:
                      items:
                        properties:
                          capacity:
                            properties:
                              sizeFree:
                                format: int64
                                type: integer
                              sizeProv:
                                format: int64
                                type: integer
                              sizeTotal:
                                format: int64
                                type: integer
                              sizeUsed:
                                format: int64
                                type: integer
                              sizeUtil:
                                format: int64
                                type: integer
                            required:
                            - sizeFree
                            - sizeProv
                            - sizeTotal
                            - sizeUsed
                            - sizeUtil
                            type: object
                          health:
                            type: string
                          model:
                            type: string
                          size:
                            format: int64
                            type: integer
                          stats:
                            items:
                              properties:
                                capacityUtil:
                                  format: int64
                                  type: integer
                                riops:
                                  format: int64
                                  type: integer
                                rtp:
                                  format: int64
                                  type: integer
                                wiops:
                                  format: int64
                                  type: integer
                                wtp:
                                  format: int64
                                  type: integer
                              type: object
                            type: array
                          status:
                            type: string
                          utilization:
                            format: int64
                            type: integer
                          uuid:
                            type: string
                        type: object
                      type: array
                    nodeUUID:
                      type: string
                  type: object
                type: array
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
    subresources:
      status: {}
