apiVersion: v1
kind: Secret
metadata:
  name: simplyblock-grafana-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  CLUSTER_SECRET: "{{ .Values.cluster.secret }}"
  GRAFANA_ENDPOINT: "{{ .Values.grafana.endpoint }}"

---
apiVersion: v1
kind: Secret
metadata:
  name: simplyblock-graylog-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  GRAYLOG_PASSWORD_SECRET: "{{ .Values.graylog.passwordSecret }}"
  GRAYLOG_ROOT_PASSWORD_SHA2: "{{ .Values.graylog.rootPasswordSha2 }}"
  MAX_NUMBER_OF_INDICES: "{{ .Values.log.maxNumberIndex }}"
