---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-local-hostpath
provisioner: openebs.io/local
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
{{- if .Values.storageclass.allowedTopologyZones }}
allowedTopologies:
- matchLabelExpressions:
  - key: topology.kubernetes.io/zone
    values:
{{- range .Values.storageclass.allowedTopologyZones }}
    - {{ . }}
{{- end }}
{{- end }}
