---
apiVersion: v1
appVersion: latest
description: Simplyblock Control Plane
name: sbcli
version: "v0.1.0"
keywords:
- simplyblock
- mgmt
- sbcli
home: https://github.com/simplyblock-io/sbcli
sources:
- https://github.com/simplyblock-io/sbcli/tree/main/simplyblock_core/scripts/charts

dependencies:
  - name: mongodb
    version: 13.16.4
    repository: https://charts.bitnami.com/bitnami
    condition: monitoring.enabled
  - name: opensearch
    version: 2.9.0
    repository: https://opensearch-project.github.io/helm-charts
    condition: monitoring.enabled
  - name: prometheus
    version: "25.18.0"
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: monitoring.enabled
  - name: openebs
    version: 3.9.0 
    repository: https://openebs.github.io/charts
    alias: openebs
    condition: openebs.enabled
  - name: jiva
    version: 3.9.0
    repository: https://openebs.github.io/charts
    alias: openebs.jiva
    condition: openebs.enabled
  - name: ingress-nginx
    version: 4.10.1
    repository: "https://kubernetes.github.io/ingress-nginx"
    alias: ingress
    condition: ingress.enabled
    