global:
  scrape_interval: 15s
  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'metricsgateway'
    static_configs:
      - targets: ['pushgateway:9091']
  - job_name: nodemetrics
    static_configs:
      - targets: ['node-exporter:9100']
