name: Docker Base Image Build

on:
  schedule:
    - cron: '0 5 * * SUN'  # Sundays at 5am
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: hamdysimplyblock
        password: ${{ secrets.DOCKER_PASS }}

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_HAMDI }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_HAMDI }}
        aws-region: us-east-1

    - name: Login to ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
      with:
        registry-type: public

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Build & Push
      run: |
        IMAGE_TAG=base_image_313

        docker buildx ls
        docker buildx create --name mybuilder --bootstrap --use
        docker buildx build --platform linux/amd64,linux/arm64 -t simplyblock/simplyblock:$IMAGE_TAG \
        -t public.ecr.aws/simply-block/simplyblock:$IMAGE_TAG -f docker/Dockerfile_base . --push

        echo "::notice title=Docker.com::simplyblock/simplyblock:$IMAGE_TAG
        echo "::notice title=AWS-ECR::public.ecr.aws/simply-block/simplyblock:$IMAGE_TAG
