name: Python Package Build

on:
  push:
    paths:
      - 'env_var'

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip twine setuptools
        pip install build
    - name: Build package
      run: python setup.py sdist --formats=zip
    - name: Publish package to pypi
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_HAMDI }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_HAMDI }}
        aws-region: eu-west-1

    - name: Publish package codeArtifact
      run: |
        aws codeartifact login --tool twine --repository sbcli --domain simplyblock --domain-owner 565979732541 --region eu-west-1
        twine upload dist/* -r codeartifact
